//
// Created by gs1010 on 25/06/20.
//

#ifndef TSPGENETICALGORITHM_SRC_GENETICALGORITHM_TSPGENETICALGORITHMOMP_H_
#define TSPGENETICALGORITHM_SRC_GENETICALGORITHM_TSPGENETICALGORITHMOMP_H_

class TSPGeneticAlgorithmOMP {

};

#endif //TSPGENETICALGORITHM_SRC_GENETICALGORITHM_TSPGENETICALGORITHMOMP_H_
